const fs = require('fs');
const path = require('path');

const files = [
  'src/config.mjs',
  'src/utils.mjs',
  'src/http.mjs',
  'src/api.mjs',
  'src/discovery.mjs',
  'src/poll.mjs',
  'src/main.mjs'
];

let bundled = `// ============================================================================
//  RUCKUS Unleashed AJAX WIPS driver — runs inside a Node-RED function node.
//  Pure light-weight JavaScript implementation focusing strictly on WIPS.
//  Auto-generated by build.js — DO NOT EDIT DIRECTLY.
// ============================================================================

`;

for (const file of files) {
  const filePath = path.join(__dirname, file);
  if (!fs.existsSync(filePath)) {
    console.error(`Error: file ${file} does not exist!`);
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  const processedLines = [];
  for (const line of lines) {
    // Strip imports (e.g. import ... from '...';)
    if (/^\s*import\s+.*?\s+from\s+['"].*?['"];?\s*$/.test(line)) {
      continue;
    }
    // Strip exports
    let processed = line;
    processed = processed.replace(/^\s*export\s+(async\s+)?function\s+/, '$1function ');
    processed = processed.replace(/^\s*export\s+const\s+/, 'const ');
    processed = processed.replace(/^\s*export\s+let\s+/, 'let ');
    processed = processed.replace(/^\s*export\s+default\s+/, '');
    processedLines.push(processed);
  }
  bundled += `// --- ${path.basename(file)} ---\n` + processedLines.join('\n') + '\n\n';
}

// Write to func.js
fs.writeFileSync(path.join(__dirname, 'func.js'), bundled, 'utf8');
console.log('✔ Successfully bundled into func.js');

// Verification: Ensure no ES6 module syntax (import/export) leaks into the bundled output
const cleanCode = bundled.replace(/\/\*[\s\S]*?\*\/|\/\/.*/g, ''); // strip comments
if (/\bimport\b/.test(cleanCode) || /\bexport\b/.test(cleanCode)) {
  console.error('Error: Bundled code contains ES6 module syntax (import/export)!');
  process.exit(1);
}

// Update ruckus_wips.json flow file
const flowPath = path.join(__dirname, 'flows/ruckus_wips.json');
if (fs.existsSync(flowPath)) {
  const flow = JSON.parse(fs.readFileSync(flowPath, 'utf8'));
  let updatedFn = false;
  let hasStatusMonitor = false;

  for (const node of flow) {
    if (node.id === 'fn_ruckus') {
      node.func = bundled;
      
      // Clear node-level env variables to avoid shadowing OS environment variables
      if (node.env) {
        delete node.env;
      }

      // Ensure zlib is added to external libraries configuration
      node.libs = node.libs || [];
      const hasZlib = node.libs.some(lib => lib.module === 'zlib');
      if (!hasZlib) {
        node.libs.push({ var: 'zlib', module: 'zlib' });
      }
      
      updatedFn = true;
    }
    if (node.id === 'status_monitor') {
      hasStatusMonitor = true;
    }
  }

  // Inject status monitor node if missing
  if (!hasStatusMonitor) {
    const statusMonitorNode = {
      id: 'status_monitor',
      type: 'status',
      z: 'ruckus_wips_tab',
      name: 'Monitor MQTT connection',
      scope: [
        'mqtt_out'
      ],
      x: 180,
      y: 340,
      wires: [
        [
          'fn_ruckus'
        ]
      ]
    };
    flow.push(statusMonitorNode);
    console.log('✔ Injected status_monitor node into flow JSON.');
  }

  if (updatedFn) {
    fs.writeFileSync(flowPath, JSON.stringify(flow, null, 2), 'utf8');
    console.log('✔ Successfully updated flows/ruckus_wips.json');
  } else {
    console.error('Error: fn_ruckus node not found in flows/ruckus_wips.json');
    process.exit(1);
  }
} else {
  console.warn('Warning: flows/ruckus_wips.json not found, skipping flow update.');
}
